name: s3-depl

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Build React App
        run: npm ci && npm run build
